package com.xinguqe.xingque_api.entity;

import java.io.Serializable;
import java.util.Date;

public class QuickLink implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_quick_link.id
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_quick_link.name
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_quick_link.sort
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_quick_link.ident
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    private String ident;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_quick_link.status
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_quick_link.create_time
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_quick_link.modified_time
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_quick_link.logo
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xq_quick_link
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_quick_link.id
     *
     * @return the value of xq_quick_link.id
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_quick_link
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    public QuickLink withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_quick_link.id
     *
     * @param id the value for xq_quick_link.id
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_quick_link.name
     *
     * @return the value of xq_quick_link.name
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_quick_link
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    public QuickLink withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_quick_link.name
     *
     * @param name the value for xq_quick_link.name
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_quick_link.sort
     *
     * @return the value of xq_quick_link.sort
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_quick_link
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    public QuickLink withSort(Integer sort) {
        this.setSort(sort);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_quick_link.sort
     *
     * @param sort the value for xq_quick_link.sort
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_quick_link.ident
     *
     * @return the value of xq_quick_link.ident
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    public String getIdent() {
        return ident;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_quick_link
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    public QuickLink withIdent(String ident) {
        this.setIdent(ident);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_quick_link.ident
     *
     * @param ident the value for xq_quick_link.ident
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    public void setIdent(String ident) {
        this.ident = ident == null ? null : ident.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_quick_link.status
     *
     * @return the value of xq_quick_link.status
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_quick_link
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    public QuickLink withStatus(Integer status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_quick_link.status
     *
     * @param status the value for xq_quick_link.status
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_quick_link.create_time
     *
     * @return the value of xq_quick_link.create_time
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_quick_link
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    public QuickLink withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_quick_link.create_time
     *
     * @param createTime the value for xq_quick_link.create_time
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_quick_link.modified_time
     *
     * @return the value of xq_quick_link.modified_time
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_quick_link
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    public QuickLink withModifiedTime(Date modifiedTime) {
        this.setModifiedTime(modifiedTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_quick_link.modified_time
     *
     * @param modifiedTime the value for xq_quick_link.modified_time
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_quick_link.logo
     *
     * @return the value of xq_quick_link.logo
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_quick_link
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    public QuickLink withLogo(String logo) {
        this.setLogo(logo);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_quick_link.logo
     *
     * @param logo the value for xq_quick_link.logo
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_quick_link
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", sort=").append(sort);
        sb.append(", ident=").append(ident);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append(", logo=").append(logo);
        sb.append("]");
        return sb.toString();
    }
}