package com.xinguqe.xingque_api.entity;

import java.io.Serializable;
import java.util.Date;

public class UserSuggest implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_suggest.id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_suggest.user_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_suggest.content
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_suggest.status
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_suggest.create_time
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_suggest.modified_time
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_suggest.images
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private String images;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xq_user_suggest
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_suggest.id
     *
     * @return the value of xq_user_suggest.id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_suggest
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserSuggest withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_suggest.id
     *
     * @param id the value for xq_user_suggest.id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_suggest.user_id
     *
     * @return the value of xq_user_suggest.user_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_suggest
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserSuggest withUserId(Integer userId) {
        this.setUserId(userId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_suggest.user_id
     *
     * @param userId the value for xq_user_suggest.user_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_suggest.content
     *
     * @return the value of xq_user_suggest.content
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_suggest
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserSuggest withContent(String content) {
        this.setContent(content);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_suggest.content
     *
     * @param content the value for xq_user_suggest.content
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_suggest.status
     *
     * @return the value of xq_user_suggest.status
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_suggest
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserSuggest withStatus(Integer status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_suggest.status
     *
     * @param status the value for xq_user_suggest.status
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_suggest.create_time
     *
     * @return the value of xq_user_suggest.create_time
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_suggest
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserSuggest withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_suggest.create_time
     *
     * @param createTime the value for xq_user_suggest.create_time
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_suggest.modified_time
     *
     * @return the value of xq_user_suggest.modified_time
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_suggest
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserSuggest withModifiedTime(Date modifiedTime) {
        this.setModifiedTime(modifiedTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_suggest.modified_time
     *
     * @param modifiedTime the value for xq_user_suggest.modified_time
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_suggest.images
     *
     * @return the value of xq_user_suggest.images
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_suggest
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserSuggest withImages(String images) {
        this.setImages(images);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_suggest.images
     *
     * @param images the value for xq_user_suggest.images
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_suggest
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", content=").append(content);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append(", images=").append(images);
        sb.append("]");
        return sb.toString();
    }
}