package com.xinguqe.xingque_api.entity;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user.id
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user.avatar
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user.name
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    private String name;
    private String username;
    private String password;
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user.sex
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user.birthday
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user.residence_province_id
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    private Integer residenceProvinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user.residence_city_id
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    private Integer residenceCityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user.residence_district_id
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    private Integer residenceDistrictId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user.birth_province_id
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    private Integer birthProvinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user.birth_city_id
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    private Integer birthCityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user.birth_district_id
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    private Integer birthDistrictId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user.wx_openid
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    private String wxOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user.wx_unionid
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    private String wxUnionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user.status
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user.create_time
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user.modified_time
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user.id
     *
     * @return the value of xq_user.id
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public User withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user.id
     *
     * @param id the value for xq_user.id
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user.avatar
     *
     * @return the value of xq_user.avatar
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public User withAvatar(String avatar) {
        this.setAvatar(avatar);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user.avatar
     *
     * @param avatar the value for xq_user.avatar
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user.name
     *
     * @return the value of xq_user.name
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public String getName() {
        return name;
    }
    public String getUsername() {
        return username;
    }
    public String getPassword() {
        return password;
    }
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public User withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user.name
     *
     * @param name the value for xq_user.name
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
    public void setUserName(String username) {
        this.username = username == null ? null : username.trim();
    }
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user.sex
     *
     * @return the value of xq_user.sex
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public User withSex(Integer sex) {
        this.setSex(sex);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user.sex
     *
     * @param sex the value for xq_user.sex
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user.birthday
     *
     * @return the value of xq_user.birthday
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public User withBirthday(String birthday) {
        this.setBirthday(birthday);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user.birthday
     *
     * @param birthday the value for xq_user.birthday
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user.residence_province_id
     *
     * @return the value of xq_user.residence_province_id
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public Integer getResidenceProvinceId() {
        return residenceProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public User withResidenceProvinceId(Integer residenceProvinceId) {
        this.setResidenceProvinceId(residenceProvinceId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user.residence_province_id
     *
     * @param residenceProvinceId the value for xq_user.residence_province_id
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public void setResidenceProvinceId(Integer residenceProvinceId) {
        this.residenceProvinceId = residenceProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user.residence_city_id
     *
     * @return the value of xq_user.residence_city_id
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public Integer getResidenceCityId() {
        return residenceCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public User withResidenceCityId(Integer residenceCityId) {
        this.setResidenceCityId(residenceCityId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user.residence_city_id
     *
     * @param residenceCityId the value for xq_user.residence_city_id
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public void setResidenceCityId(Integer residenceCityId) {
        this.residenceCityId = residenceCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user.residence_district_id
     *
     * @return the value of xq_user.residence_district_id
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public Integer getResidenceDistrictId() {
        return residenceDistrictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public User withResidenceDistrictId(Integer residenceDistrictId) {
        this.setResidenceDistrictId(residenceDistrictId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user.residence_district_id
     *
     * @param residenceDistrictId the value for xq_user.residence_district_id
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public void setResidenceDistrictId(Integer residenceDistrictId) {
        this.residenceDistrictId = residenceDistrictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user.birth_province_id
     *
     * @return the value of xq_user.birth_province_id
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public Integer getBirthProvinceId() {
        return birthProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public User withBirthProvinceId(Integer birthProvinceId) {
        this.setBirthProvinceId(birthProvinceId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user.birth_province_id
     *
     * @param birthProvinceId the value for xq_user.birth_province_id
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public void setBirthProvinceId(Integer birthProvinceId) {
        this.birthProvinceId = birthProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user.birth_city_id
     *
     * @return the value of xq_user.birth_city_id
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public Integer getBirthCityId() {
        return birthCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public User withBirthCityId(Integer birthCityId) {
        this.setBirthCityId(birthCityId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user.birth_city_id
     *
     * @param birthCityId the value for xq_user.birth_city_id
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public void setBirthCityId(Integer birthCityId) {
        this.birthCityId = birthCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user.birth_district_id
     *
     * @return the value of xq_user.birth_district_id
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public Integer getBirthDistrictId() {
        return birthDistrictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public User withBirthDistrictId(Integer birthDistrictId) {
        this.setBirthDistrictId(birthDistrictId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user.birth_district_id
     *
     * @param birthDistrictId the value for xq_user.birth_district_id
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public void setBirthDistrictId(Integer birthDistrictId) {
        this.birthDistrictId = birthDistrictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user.wx_openid
     *
     * @return the value of xq_user.wx_openid
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public String getWxOpenid() {
        return wxOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public User withWxOpenid(String wxOpenid) {
        this.setWxOpenid(wxOpenid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user.wx_openid
     *
     * @param wxOpenid the value for xq_user.wx_openid
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public void setWxOpenid(String wxOpenid) {
        this.wxOpenid = wxOpenid == null ? null : wxOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user.wx_unionid
     *
     * @return the value of xq_user.wx_unionid
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public String getWxUnionid() {
        return wxUnionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public User withWxUnionid(String wxUnionid) {
        this.setWxUnionid(wxUnionid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user.wx_unionid
     *
     * @param wxUnionid the value for xq_user.wx_unionid
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public void setWxUnionid(String wxUnionid) {
        this.wxUnionid = wxUnionid == null ? null : wxUnionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user.status
     *
     * @return the value of xq_user.status
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public User withStatus(Integer status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user.status
     *
     * @param status the value for xq_user.status
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user.create_time
     *
     * @return the value of xq_user.create_time
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public User withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user.create_time
     *
     * @param createTime the value for xq_user.create_time
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user.modified_time
     *
     * @return the value of xq_user.modified_time
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public User withModifiedTime(Date modifiedTime) {
        this.setModifiedTime(modifiedTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user.modified_time
     *
     * @param modifiedTime the value for xq_user.modified_time
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", avatar=").append(avatar);
        sb.append(", name=").append(name);
        sb.append(", sex=").append(sex);
        sb.append(", birthday=").append(birthday);
        sb.append(", residenceProvinceId=").append(residenceProvinceId);
        sb.append(", residenceCityId=").append(residenceCityId);
        sb.append(", residenceDistrictId=").append(residenceDistrictId);
        sb.append(", birthProvinceId=").append(birthProvinceId);
        sb.append(", birthCityId=").append(birthCityId);
        sb.append(", birthDistrictId=").append(birthDistrictId);
        sb.append(", wxOpenid=").append(wxOpenid);
        sb.append(", wxUnionid=").append(wxUnionid);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append("]");
        return sb.toString();
    }
}