package com.xinguqe.xingque_api.entity;

import java.io.Serializable;

public class UserTrigramRecordWithBLOBs extends UserTrigramRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_trigram_record.input
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private String input;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_trigram_record.output
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private String output;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_trigram_record.extras
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private String extras;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_trigram_record.input
     *
     * @return the value of xq_user_trigram_record.input
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public String getInput() {
        return input;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserTrigramRecordWithBLOBs withInput(String input) {
        this.setInput(input);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_trigram_record.input
     *
     * @param input the value for xq_user_trigram_record.input
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setInput(String input) {
        this.input = input == null ? null : input.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_trigram_record.output
     *
     * @return the value of xq_user_trigram_record.output
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public String getOutput() {
        return output;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserTrigramRecordWithBLOBs withOutput(String output) {
        this.setOutput(output);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_trigram_record.output
     *
     * @param output the value for xq_user_trigram_record.output
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setOutput(String output) {
        this.output = output == null ? null : output.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_trigram_record.extras
     *
     * @return the value of xq_user_trigram_record.extras
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public String getExtras() {
        return extras;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserTrigramRecordWithBLOBs withExtras(String extras) {
        this.setExtras(extras);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_trigram_record.extras
     *
     * @param extras the value for xq_user_trigram_record.extras
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setExtras(String extras) {
        this.extras = extras == null ? null : extras.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", input=").append(input);
        sb.append(", output=").append(output);
        sb.append(", extras=").append(extras);
        sb.append("]");
        return sb.toString();
    }
}