package com.xinguqe.xingque_api.entity;

import java.io.Serializable;
import java.util.Date;

public class UserTrigramRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_trigram_record.id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_trigram_record.user_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_trigram_record.type
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_trigram_record.status
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_trigram_record.input_key
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private String inputKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_trigram_record.save_type
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Integer saveType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_trigram_record.create_time
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_trigram_record.modified_time
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_trigram_record.id
     *
     * @return the value of xq_user_trigram_record.id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserTrigramRecord withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_trigram_record.id
     *
     * @param id the value for xq_user_trigram_record.id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_trigram_record.user_id
     *
     * @return the value of xq_user_trigram_record.user_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserTrigramRecord withUserId(Integer userId) {
        this.setUserId(userId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_trigram_record.user_id
     *
     * @param userId the value for xq_user_trigram_record.user_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_trigram_record.type
     *
     * @return the value of xq_user_trigram_record.type
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserTrigramRecord withType(Integer type) {
        this.setType(type);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_trigram_record.type
     *
     * @param type the value for xq_user_trigram_record.type
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_trigram_record.status
     *
     * @return the value of xq_user_trigram_record.status
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserTrigramRecord withStatus(Integer status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_trigram_record.status
     *
     * @param status the value for xq_user_trigram_record.status
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_trigram_record.input_key
     *
     * @return the value of xq_user_trigram_record.input_key
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public String getInputKey() {
        return inputKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserTrigramRecord withInputKey(String inputKey) {
        this.setInputKey(inputKey);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_trigram_record.input_key
     *
     * @param inputKey the value for xq_user_trigram_record.input_key
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setInputKey(String inputKey) {
        this.inputKey = inputKey == null ? null : inputKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_trigram_record.save_type
     *
     * @return the value of xq_user_trigram_record.save_type
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Integer getSaveType() {
        return saveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserTrigramRecord withSaveType(Integer saveType) {
        this.setSaveType(saveType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_trigram_record.save_type
     *
     * @param saveType the value for xq_user_trigram_record.save_type
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setSaveType(Integer saveType) {
        this.saveType = saveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_trigram_record.create_time
     *
     * @return the value of xq_user_trigram_record.create_time
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserTrigramRecord withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_trigram_record.create_time
     *
     * @param createTime the value for xq_user_trigram_record.create_time
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_trigram_record.modified_time
     *
     * @return the value of xq_user_trigram_record.modified_time
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserTrigramRecord withModifiedTime(Date modifiedTime) {
        this.setModifiedTime(modifiedTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_trigram_record.modified_time
     *
     * @param modifiedTime the value for xq_user_trigram_record.modified_time
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", type=").append(type);
        sb.append(", status=").append(status);
        sb.append(", inputKey=").append(inputKey);
        sb.append(", saveType=").append(saveType);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append("]");
        return sb.toString();
    }
}