package com.xinguqe.xingque_api.entity;

import java.io.Serializable;
import java.util.Date;

public class UserConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_config.id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_config.user_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_config.apparent_solar_time
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Integer apparentSolarTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_config.qimen_type
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Integer qimenType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_config.liuren_type
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Integer liurenType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_config.status
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_config.create_time
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_config.modified_time
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xq_user_config
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_config.id
     *
     * @return the value of xq_user_config.id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_config
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserConfig withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_config.id
     *
     * @param id the value for xq_user_config.id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_config.user_id
     *
     * @return the value of xq_user_config.user_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_config
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserConfig withUserId(Integer userId) {
        this.setUserId(userId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_config.user_id
     *
     * @param userId the value for xq_user_config.user_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_config.apparent_solar_time
     *
     * @return the value of xq_user_config.apparent_solar_time
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Integer getApparentSolarTime() {
        return apparentSolarTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_config
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserConfig withApparentSolarTime(Integer apparentSolarTime) {
        this.setApparentSolarTime(apparentSolarTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_config.apparent_solar_time
     *
     * @param apparentSolarTime the value for xq_user_config.apparent_solar_time
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setApparentSolarTime(Integer apparentSolarTime) {
        this.apparentSolarTime = apparentSolarTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_config.qimen_type
     *
     * @return the value of xq_user_config.qimen_type
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Integer getQimenType() {
        return qimenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_config
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserConfig withQimenType(Integer qimenType) {
        this.setQimenType(qimenType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_config.qimen_type
     *
     * @param qimenType the value for xq_user_config.qimen_type
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setQimenType(Integer qimenType) {
        this.qimenType = qimenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_config.liuren_type
     *
     * @return the value of xq_user_config.liuren_type
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Integer getLiurenType() {
        return liurenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_config
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserConfig withLiurenType(Integer liurenType) {
        this.setLiurenType(liurenType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_config.liuren_type
     *
     * @param liurenType the value for xq_user_config.liuren_type
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setLiurenType(Integer liurenType) {
        this.liurenType = liurenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_config.status
     *
     * @return the value of xq_user_config.status
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_config
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserConfig withStatus(Integer status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_config.status
     *
     * @param status the value for xq_user_config.status
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_config.create_time
     *
     * @return the value of xq_user_config.create_time
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_config
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserConfig withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_config.create_time
     *
     * @param createTime the value for xq_user_config.create_time
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_config.modified_time
     *
     * @return the value of xq_user_config.modified_time
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_config
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserConfig withModifiedTime(Date modifiedTime) {
        this.setModifiedTime(modifiedTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_config.modified_time
     *
     * @param modifiedTime the value for xq_user_config.modified_time
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_config
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", apparentSolarTime=").append(apparentSolarTime);
        sb.append(", qimenType=").append(qimenType);
        sb.append(", liurenType=").append(liurenType);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append("]");
        return sb.toString();
    }
}