package com.xinguqe.xingque_api.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public UserExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAvatarIsNull() {
            addCriterion("avatar is null");
            return (Criteria) this;
        }

        public Criteria andAvatarIsNotNull() {
            addCriterion("avatar is not null");
            return (Criteria) this;
        }

        public Criteria andAvatarEqualTo(String value) {
            addCriterion("avatar =", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotEqualTo(String value) {
            addCriterion("avatar <>", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarGreaterThan(String value) {
            addCriterion("avatar >", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarGreaterThanOrEqualTo(String value) {
            addCriterion("avatar >=", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarLessThan(String value) {
            addCriterion("avatar <", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarLessThanOrEqualTo(String value) {
            addCriterion("avatar <=", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarLike(String value) {
            addCriterion("avatar like", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotLike(String value) {
            addCriterion("avatar not like", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarIn(List<String> values) {
            addCriterion("avatar in", values, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotIn(List<String> values) {
            addCriterion("avatar not in", values, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarBetween(String value1, String value2) {
            addCriterion("avatar between", value1, value2, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotBetween(String value1, String value2) {
            addCriterion("avatar not between", value1, value2, "avatar");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }


        public Criteria andUserNameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(Integer value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(Integer value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(Integer value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(Integer value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(Integer value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(Integer value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<Integer> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<Integer> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(Integer value1, Integer value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(Integer value1, Integer value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("birthday is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("birthday is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(String value) {
            addCriterion("birthday =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(String value) {
            addCriterion("birthday <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(String value) {
            addCriterion("birthday >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(String value) {
            addCriterion("birthday >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(String value) {
            addCriterion("birthday <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(String value) {
            addCriterion("birthday <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLike(String value) {
            addCriterion("birthday like", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotLike(String value) {
            addCriterion("birthday not like", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<String> values) {
            addCriterion("birthday in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<String> values) {
            addCriterion("birthday not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(String value1, String value2) {
            addCriterion("birthday between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(String value1, String value2) {
            addCriterion("birthday not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andResidenceProvinceIdIsNull() {
            addCriterion("residence_province_id is null");
            return (Criteria) this;
        }

        public Criteria andResidenceProvinceIdIsNotNull() {
            addCriterion("residence_province_id is not null");
            return (Criteria) this;
        }

        public Criteria andResidenceProvinceIdEqualTo(Integer value) {
            addCriterion("residence_province_id =", value, "residenceProvinceId");
            return (Criteria) this;
        }

        public Criteria andResidenceProvinceIdNotEqualTo(Integer value) {
            addCriterion("residence_province_id <>", value, "residenceProvinceId");
            return (Criteria) this;
        }

        public Criteria andResidenceProvinceIdGreaterThan(Integer value) {
            addCriterion("residence_province_id >", value, "residenceProvinceId");
            return (Criteria) this;
        }

        public Criteria andResidenceProvinceIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("residence_province_id >=", value, "residenceProvinceId");
            return (Criteria) this;
        }

        public Criteria andResidenceProvinceIdLessThan(Integer value) {
            addCriterion("residence_province_id <", value, "residenceProvinceId");
            return (Criteria) this;
        }

        public Criteria andResidenceProvinceIdLessThanOrEqualTo(Integer value) {
            addCriterion("residence_province_id <=", value, "residenceProvinceId");
            return (Criteria) this;
        }

        public Criteria andResidenceProvinceIdIn(List<Integer> values) {
            addCriterion("residence_province_id in", values, "residenceProvinceId");
            return (Criteria) this;
        }

        public Criteria andResidenceProvinceIdNotIn(List<Integer> values) {
            addCriterion("residence_province_id not in", values, "residenceProvinceId");
            return (Criteria) this;
        }

        public Criteria andResidenceProvinceIdBetween(Integer value1, Integer value2) {
            addCriterion("residence_province_id between", value1, value2, "residenceProvinceId");
            return (Criteria) this;
        }

        public Criteria andResidenceProvinceIdNotBetween(Integer value1, Integer value2) {
            addCriterion("residence_province_id not between", value1, value2, "residenceProvinceId");
            return (Criteria) this;
        }

        public Criteria andResidenceCityIdIsNull() {
            addCriterion("residence_city_id is null");
            return (Criteria) this;
        }

        public Criteria andResidenceCityIdIsNotNull() {
            addCriterion("residence_city_id is not null");
            return (Criteria) this;
        }

        public Criteria andResidenceCityIdEqualTo(Integer value) {
            addCriterion("residence_city_id =", value, "residenceCityId");
            return (Criteria) this;
        }

        public Criteria andResidenceCityIdNotEqualTo(Integer value) {
            addCriterion("residence_city_id <>", value, "residenceCityId");
            return (Criteria) this;
        }

        public Criteria andResidenceCityIdGreaterThan(Integer value) {
            addCriterion("residence_city_id >", value, "residenceCityId");
            return (Criteria) this;
        }

        public Criteria andResidenceCityIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("residence_city_id >=", value, "residenceCityId");
            return (Criteria) this;
        }

        public Criteria andResidenceCityIdLessThan(Integer value) {
            addCriterion("residence_city_id <", value, "residenceCityId");
            return (Criteria) this;
        }

        public Criteria andResidenceCityIdLessThanOrEqualTo(Integer value) {
            addCriterion("residence_city_id <=", value, "residenceCityId");
            return (Criteria) this;
        }

        public Criteria andResidenceCityIdIn(List<Integer> values) {
            addCriterion("residence_city_id in", values, "residenceCityId");
            return (Criteria) this;
        }

        public Criteria andResidenceCityIdNotIn(List<Integer> values) {
            addCriterion("residence_city_id not in", values, "residenceCityId");
            return (Criteria) this;
        }

        public Criteria andResidenceCityIdBetween(Integer value1, Integer value2) {
            addCriterion("residence_city_id between", value1, value2, "residenceCityId");
            return (Criteria) this;
        }

        public Criteria andResidenceCityIdNotBetween(Integer value1, Integer value2) {
            addCriterion("residence_city_id not between", value1, value2, "residenceCityId");
            return (Criteria) this;
        }

        public Criteria andResidenceDistrictIdIsNull() {
            addCriterion("residence_district_id is null");
            return (Criteria) this;
        }

        public Criteria andResidenceDistrictIdIsNotNull() {
            addCriterion("residence_district_id is not null");
            return (Criteria) this;
        }

        public Criteria andResidenceDistrictIdEqualTo(Integer value) {
            addCriterion("residence_district_id =", value, "residenceDistrictId");
            return (Criteria) this;
        }

        public Criteria andResidenceDistrictIdNotEqualTo(Integer value) {
            addCriterion("residence_district_id <>", value, "residenceDistrictId");
            return (Criteria) this;
        }

        public Criteria andResidenceDistrictIdGreaterThan(Integer value) {
            addCriterion("residence_district_id >", value, "residenceDistrictId");
            return (Criteria) this;
        }

        public Criteria andResidenceDistrictIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("residence_district_id >=", value, "residenceDistrictId");
            return (Criteria) this;
        }

        public Criteria andResidenceDistrictIdLessThan(Integer value) {
            addCriterion("residence_district_id <", value, "residenceDistrictId");
            return (Criteria) this;
        }

        public Criteria andResidenceDistrictIdLessThanOrEqualTo(Integer value) {
            addCriterion("residence_district_id <=", value, "residenceDistrictId");
            return (Criteria) this;
        }

        public Criteria andResidenceDistrictIdIn(List<Integer> values) {
            addCriterion("residence_district_id in", values, "residenceDistrictId");
            return (Criteria) this;
        }

        public Criteria andResidenceDistrictIdNotIn(List<Integer> values) {
            addCriterion("residence_district_id not in", values, "residenceDistrictId");
            return (Criteria) this;
        }

        public Criteria andResidenceDistrictIdBetween(Integer value1, Integer value2) {
            addCriterion("residence_district_id between", value1, value2, "residenceDistrictId");
            return (Criteria) this;
        }

        public Criteria andResidenceDistrictIdNotBetween(Integer value1, Integer value2) {
            addCriterion("residence_district_id not between", value1, value2, "residenceDistrictId");
            return (Criteria) this;
        }

        public Criteria andBirthProvinceIdIsNull() {
            addCriterion("birth_province_id is null");
            return (Criteria) this;
        }

        public Criteria andBirthProvinceIdIsNotNull() {
            addCriterion("birth_province_id is not null");
            return (Criteria) this;
        }

        public Criteria andBirthProvinceIdEqualTo(Integer value) {
            addCriterion("birth_province_id =", value, "birthProvinceId");
            return (Criteria) this;
        }

        public Criteria andBirthProvinceIdNotEqualTo(Integer value) {
            addCriterion("birth_province_id <>", value, "birthProvinceId");
            return (Criteria) this;
        }

        public Criteria andBirthProvinceIdGreaterThan(Integer value) {
            addCriterion("birth_province_id >", value, "birthProvinceId");
            return (Criteria) this;
        }

        public Criteria andBirthProvinceIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("birth_province_id >=", value, "birthProvinceId");
            return (Criteria) this;
        }

        public Criteria andBirthProvinceIdLessThan(Integer value) {
            addCriterion("birth_province_id <", value, "birthProvinceId");
            return (Criteria) this;
        }

        public Criteria andBirthProvinceIdLessThanOrEqualTo(Integer value) {
            addCriterion("birth_province_id <=", value, "birthProvinceId");
            return (Criteria) this;
        }

        public Criteria andBirthProvinceIdIn(List<Integer> values) {
            addCriterion("birth_province_id in", values, "birthProvinceId");
            return (Criteria) this;
        }

        public Criteria andBirthProvinceIdNotIn(List<Integer> values) {
            addCriterion("birth_province_id not in", values, "birthProvinceId");
            return (Criteria) this;
        }

        public Criteria andBirthProvinceIdBetween(Integer value1, Integer value2) {
            addCriterion("birth_province_id between", value1, value2, "birthProvinceId");
            return (Criteria) this;
        }

        public Criteria andBirthProvinceIdNotBetween(Integer value1, Integer value2) {
            addCriterion("birth_province_id not between", value1, value2, "birthProvinceId");
            return (Criteria) this;
        }

        public Criteria andBirthCityIdIsNull() {
            addCriterion("birth_city_id is null");
            return (Criteria) this;
        }

        public Criteria andBirthCityIdIsNotNull() {
            addCriterion("birth_city_id is not null");
            return (Criteria) this;
        }

        public Criteria andBirthCityIdEqualTo(Integer value) {
            addCriterion("birth_city_id =", value, "birthCityId");
            return (Criteria) this;
        }

        public Criteria andBirthCityIdNotEqualTo(Integer value) {
            addCriterion("birth_city_id <>", value, "birthCityId");
            return (Criteria) this;
        }

        public Criteria andBirthCityIdGreaterThan(Integer value) {
            addCriterion("birth_city_id >", value, "birthCityId");
            return (Criteria) this;
        }

        public Criteria andBirthCityIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("birth_city_id >=", value, "birthCityId");
            return (Criteria) this;
        }

        public Criteria andBirthCityIdLessThan(Integer value) {
            addCriterion("birth_city_id <", value, "birthCityId");
            return (Criteria) this;
        }

        public Criteria andBirthCityIdLessThanOrEqualTo(Integer value) {
            addCriterion("birth_city_id <=", value, "birthCityId");
            return (Criteria) this;
        }

        public Criteria andBirthCityIdIn(List<Integer> values) {
            addCriterion("birth_city_id in", values, "birthCityId");
            return (Criteria) this;
        }

        public Criteria andBirthCityIdNotIn(List<Integer> values) {
            addCriterion("birth_city_id not in", values, "birthCityId");
            return (Criteria) this;
        }

        public Criteria andBirthCityIdBetween(Integer value1, Integer value2) {
            addCriterion("birth_city_id between", value1, value2, "birthCityId");
            return (Criteria) this;
        }

        public Criteria andBirthCityIdNotBetween(Integer value1, Integer value2) {
            addCriterion("birth_city_id not between", value1, value2, "birthCityId");
            return (Criteria) this;
        }

        public Criteria andBirthDistrictIdIsNull() {
            addCriterion("birth_district_id is null");
            return (Criteria) this;
        }

        public Criteria andBirthDistrictIdIsNotNull() {
            addCriterion("birth_district_id is not null");
            return (Criteria) this;
        }

        public Criteria andBirthDistrictIdEqualTo(Integer value) {
            addCriterion("birth_district_id =", value, "birthDistrictId");
            return (Criteria) this;
        }

        public Criteria andBirthDistrictIdNotEqualTo(Integer value) {
            addCriterion("birth_district_id <>", value, "birthDistrictId");
            return (Criteria) this;
        }

        public Criteria andBirthDistrictIdGreaterThan(Integer value) {
            addCriterion("birth_district_id >", value, "birthDistrictId");
            return (Criteria) this;
        }

        public Criteria andBirthDistrictIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("birth_district_id >=", value, "birthDistrictId");
            return (Criteria) this;
        }

        public Criteria andBirthDistrictIdLessThan(Integer value) {
            addCriterion("birth_district_id <", value, "birthDistrictId");
            return (Criteria) this;
        }

        public Criteria andBirthDistrictIdLessThanOrEqualTo(Integer value) {
            addCriterion("birth_district_id <=", value, "birthDistrictId");
            return (Criteria) this;
        }

        public Criteria andBirthDistrictIdIn(List<Integer> values) {
            addCriterion("birth_district_id in", values, "birthDistrictId");
            return (Criteria) this;
        }

        public Criteria andBirthDistrictIdNotIn(List<Integer> values) {
            addCriterion("birth_district_id not in", values, "birthDistrictId");
            return (Criteria) this;
        }

        public Criteria andBirthDistrictIdBetween(Integer value1, Integer value2) {
            addCriterion("birth_district_id between", value1, value2, "birthDistrictId");
            return (Criteria) this;
        }

        public Criteria andBirthDistrictIdNotBetween(Integer value1, Integer value2) {
            addCriterion("birth_district_id not between", value1, value2, "birthDistrictId");
            return (Criteria) this;
        }

        public Criteria andWxOpenidIsNull() {
            addCriterion("wx_openid is null");
            return (Criteria) this;
        }

        public Criteria andWxOpenidIsNotNull() {
            addCriterion("wx_openid is not null");
            return (Criteria) this;
        }

        public Criteria andWxOpenidEqualTo(String value) {
            addCriterion("wx_openid =", value, "wxOpenid");
            return (Criteria) this;
        }

        public Criteria andWxOpenidNotEqualTo(String value) {
            addCriterion("wx_openid <>", value, "wxOpenid");
            return (Criteria) this;
        }

        public Criteria andWxOpenidGreaterThan(String value) {
            addCriterion("wx_openid >", value, "wxOpenid");
            return (Criteria) this;
        }

        public Criteria andWxOpenidGreaterThanOrEqualTo(String value) {
            addCriterion("wx_openid >=", value, "wxOpenid");
            return (Criteria) this;
        }

        public Criteria andWxOpenidLessThan(String value) {
            addCriterion("wx_openid <", value, "wxOpenid");
            return (Criteria) this;
        }

        public Criteria andWxOpenidLessThanOrEqualTo(String value) {
            addCriterion("wx_openid <=", value, "wxOpenid");
            return (Criteria) this;
        }

        public Criteria andWxOpenidLike(String value) {
            addCriterion("wx_openid like", value, "wxOpenid");
            return (Criteria) this;
        }

        public Criteria andWxOpenidNotLike(String value) {
            addCriterion("wx_openid not like", value, "wxOpenid");
            return (Criteria) this;
        }

        public Criteria andWxOpenidIn(List<String> values) {
            addCriterion("wx_openid in", values, "wxOpenid");
            return (Criteria) this;
        }

        public Criteria andWxOpenidNotIn(List<String> values) {
            addCriterion("wx_openid not in", values, "wxOpenid");
            return (Criteria) this;
        }

        public Criteria andWxOpenidBetween(String value1, String value2) {
            addCriterion("wx_openid between", value1, value2, "wxOpenid");
            return (Criteria) this;
        }

        public Criteria andWxOpenidNotBetween(String value1, String value2) {
            addCriterion("wx_openid not between", value1, value2, "wxOpenid");
            return (Criteria) this;
        }

        public Criteria andWxUnionidIsNull() {
            addCriterion("wx_unionid is null");
            return (Criteria) this;
        }

        public Criteria andWxUnionidIsNotNull() {
            addCriterion("wx_unionid is not null");
            return (Criteria) this;
        }

        public Criteria andWxUnionidEqualTo(String value) {
            addCriterion("wx_unionid =", value, "wxUnionid");
            return (Criteria) this;
        }

        public Criteria andWxUnionidNotEqualTo(String value) {
            addCriterion("wx_unionid <>", value, "wxUnionid");
            return (Criteria) this;
        }

        public Criteria andWxUnionidGreaterThan(String value) {
            addCriterion("wx_unionid >", value, "wxUnionid");
            return (Criteria) this;
        }

        public Criteria andWxUnionidGreaterThanOrEqualTo(String value) {
            addCriterion("wx_unionid >=", value, "wxUnionid");
            return (Criteria) this;
        }

        public Criteria andWxUnionidLessThan(String value) {
            addCriterion("wx_unionid <", value, "wxUnionid");
            return (Criteria) this;
        }

        public Criteria andWxUnionidLessThanOrEqualTo(String value) {
            addCriterion("wx_unionid <=", value, "wxUnionid");
            return (Criteria) this;
        }

        public Criteria andWxUnionidLike(String value) {
            addCriterion("wx_unionid like", value, "wxUnionid");
            return (Criteria) this;
        }

        public Criteria andWxUnionidNotLike(String value) {
            addCriterion("wx_unionid not like", value, "wxUnionid");
            return (Criteria) this;
        }

        public Criteria andWxUnionidIn(List<String> values) {
            addCriterion("wx_unionid in", values, "wxUnionid");
            return (Criteria) this;
        }

        public Criteria andWxUnionidNotIn(List<String> values) {
            addCriterion("wx_unionid not in", values, "wxUnionid");
            return (Criteria) this;
        }

        public Criteria andWxUnionidBetween(String value1, String value2) {
            addCriterion("wx_unionid between", value1, value2, "wxUnionid");
            return (Criteria) this;
        }

        public Criteria andWxUnionidNotBetween(String value1, String value2) {
            addCriterion("wx_unionid not between", value1, value2, "wxUnionid");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIsNull() {
            addCriterion("modified_time is null");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIsNotNull() {
            addCriterion("modified_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeEqualTo(Date value) {
            addCriterion("modified_time =", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotEqualTo(Date value) {
            addCriterion("modified_time <>", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeGreaterThan(Date value) {
            addCriterion("modified_time >", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modified_time >=", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeLessThan(Date value) {
            addCriterion("modified_time <", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeLessThanOrEqualTo(Date value) {
            addCriterion("modified_time <=", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIn(List<Date> values) {
            addCriterion("modified_time in", values, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotIn(List<Date> values) {
            addCriterion("modified_time not in", values, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeBetween(Date value1, Date value2) {
            addCriterion("modified_time between", value1, value2, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotBetween(Date value1, Date value2) {
            addCriterion("modified_time not between", value1, value2, "modifiedTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xq_user
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 22 17:37:50 CST 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}