package com.xinguqe.xingque_api.entity;

import java.io.Serializable;
import java.util.Date;

public class UserBehavior implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_behavior.id
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_behavior.user_id
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_behavior.module
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    private String module;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_behavior.operate
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    private String operate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_behavior.status
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_behavior.create_time
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_behavior.modified_time
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xq_user_behavior
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_behavior.id
     *
     * @return the value of xq_user_behavior.id
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_behavior
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    public UserBehavior withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_behavior.id
     *
     * @param id the value for xq_user_behavior.id
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_behavior.user_id
     *
     * @return the value of xq_user_behavior.user_id
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_behavior
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    public UserBehavior withUserId(Integer userId) {
        this.setUserId(userId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_behavior.user_id
     *
     * @param userId the value for xq_user_behavior.user_id
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_behavior.module
     *
     * @return the value of xq_user_behavior.module
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_behavior
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    public UserBehavior withModule(String module) {
        this.setModule(module);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_behavior.module
     *
     * @param module the value for xq_user_behavior.module
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    public void setModule(String module) {
        this.module = module == null ? null : module.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_behavior.operate
     *
     * @return the value of xq_user_behavior.operate
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    public String getOperate() {
        return operate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_behavior
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    public UserBehavior withOperate(String operate) {
        this.setOperate(operate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_behavior.operate
     *
     * @param operate the value for xq_user_behavior.operate
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    public void setOperate(String operate) {
        this.operate = operate == null ? null : operate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_behavior.status
     *
     * @return the value of xq_user_behavior.status
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_behavior
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    public UserBehavior withStatus(Integer status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_behavior.status
     *
     * @param status the value for xq_user_behavior.status
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_behavior.create_time
     *
     * @return the value of xq_user_behavior.create_time
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_behavior
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    public UserBehavior withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_behavior.create_time
     *
     * @param createTime the value for xq_user_behavior.create_time
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_behavior.modified_time
     *
     * @return the value of xq_user_behavior.modified_time
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_behavior
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    public UserBehavior withModifiedTime(Date modifiedTime) {
        this.setModifiedTime(modifiedTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_behavior.modified_time
     *
     * @param modifiedTime the value for xq_user_behavior.modified_time
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_behavior
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", module=").append(module);
        sb.append(", operate=").append(operate);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append("]");
        return sb.toString();
    }
}