package com.xinguqe.xingque_api.entity;

import java.io.Serializable;
import java.util.Date;

public class UserTrigramBook implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_trigram_book.id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_trigram_book.user_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_trigram_book.name
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_trigram_book.sex
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_trigram_book.birthday
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_trigram_book.residence_province_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Integer residenceProvinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_trigram_book.residence_city_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Integer residenceCityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_trigram_book.residence_district_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Integer residenceDistrictId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_trigram_book.birth_province_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Integer birthProvinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_trigram_book.birth_city_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Integer birthCityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_trigram_book.birth_district_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Integer birthDistrictId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_trigram_book.relation
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private String relation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_trigram_book.status
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_trigram_book.create_time
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xq_user_trigram_book.modified_time
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_trigram_book.id
     *
     * @return the value of xq_user_trigram_book.id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserTrigramBook withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_trigram_book.id
     *
     * @param id the value for xq_user_trigram_book.id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_trigram_book.user_id
     *
     * @return the value of xq_user_trigram_book.user_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserTrigramBook withUserId(Integer userId) {
        this.setUserId(userId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_trigram_book.user_id
     *
     * @param userId the value for xq_user_trigram_book.user_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_trigram_book.name
     *
     * @return the value of xq_user_trigram_book.name
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserTrigramBook withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_trigram_book.name
     *
     * @param name the value for xq_user_trigram_book.name
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_trigram_book.sex
     *
     * @return the value of xq_user_trigram_book.sex
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserTrigramBook withSex(Integer sex) {
        this.setSex(sex);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_trigram_book.sex
     *
     * @param sex the value for xq_user_trigram_book.sex
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_trigram_book.birthday
     *
     * @return the value of xq_user_trigram_book.birthday
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserTrigramBook withBirthday(String birthday) {
        this.setBirthday(birthday);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_trigram_book.birthday
     *
     * @param birthday the value for xq_user_trigram_book.birthday
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_trigram_book.residence_province_id
     *
     * @return the value of xq_user_trigram_book.residence_province_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Integer getResidenceProvinceId() {
        return residenceProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserTrigramBook withResidenceProvinceId(Integer residenceProvinceId) {
        this.setResidenceProvinceId(residenceProvinceId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_trigram_book.residence_province_id
     *
     * @param residenceProvinceId the value for xq_user_trigram_book.residence_province_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setResidenceProvinceId(Integer residenceProvinceId) {
        this.residenceProvinceId = residenceProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_trigram_book.residence_city_id
     *
     * @return the value of xq_user_trigram_book.residence_city_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Integer getResidenceCityId() {
        return residenceCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserTrigramBook withResidenceCityId(Integer residenceCityId) {
        this.setResidenceCityId(residenceCityId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_trigram_book.residence_city_id
     *
     * @param residenceCityId the value for xq_user_trigram_book.residence_city_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setResidenceCityId(Integer residenceCityId) {
        this.residenceCityId = residenceCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_trigram_book.residence_district_id
     *
     * @return the value of xq_user_trigram_book.residence_district_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Integer getResidenceDistrictId() {
        return residenceDistrictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserTrigramBook withResidenceDistrictId(Integer residenceDistrictId) {
        this.setResidenceDistrictId(residenceDistrictId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_trigram_book.residence_district_id
     *
     * @param residenceDistrictId the value for xq_user_trigram_book.residence_district_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setResidenceDistrictId(Integer residenceDistrictId) {
        this.residenceDistrictId = residenceDistrictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_trigram_book.birth_province_id
     *
     * @return the value of xq_user_trigram_book.birth_province_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Integer getBirthProvinceId() {
        return birthProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserTrigramBook withBirthProvinceId(Integer birthProvinceId) {
        this.setBirthProvinceId(birthProvinceId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_trigram_book.birth_province_id
     *
     * @param birthProvinceId the value for xq_user_trigram_book.birth_province_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setBirthProvinceId(Integer birthProvinceId) {
        this.birthProvinceId = birthProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_trigram_book.birth_city_id
     *
     * @return the value of xq_user_trigram_book.birth_city_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Integer getBirthCityId() {
        return birthCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserTrigramBook withBirthCityId(Integer birthCityId) {
        this.setBirthCityId(birthCityId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_trigram_book.birth_city_id
     *
     * @param birthCityId the value for xq_user_trigram_book.birth_city_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setBirthCityId(Integer birthCityId) {
        this.birthCityId = birthCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_trigram_book.birth_district_id
     *
     * @return the value of xq_user_trigram_book.birth_district_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Integer getBirthDistrictId() {
        return birthDistrictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserTrigramBook withBirthDistrictId(Integer birthDistrictId) {
        this.setBirthDistrictId(birthDistrictId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_trigram_book.birth_district_id
     *
     * @param birthDistrictId the value for xq_user_trigram_book.birth_district_id
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setBirthDistrictId(Integer birthDistrictId) {
        this.birthDistrictId = birthDistrictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_trigram_book.relation
     *
     * @return the value of xq_user_trigram_book.relation
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public String getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserTrigramBook withRelation(String relation) {
        this.setRelation(relation);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_trigram_book.relation
     *
     * @param relation the value for xq_user_trigram_book.relation
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setRelation(String relation) {
        this.relation = relation == null ? null : relation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_trigram_book.status
     *
     * @return the value of xq_user_trigram_book.status
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserTrigramBook withStatus(Integer status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_trigram_book.status
     *
     * @param status the value for xq_user_trigram_book.status
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_trigram_book.create_time
     *
     * @return the value of xq_user_trigram_book.create_time
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserTrigramBook withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_trigram_book.create_time
     *
     * @param createTime the value for xq_user_trigram_book.create_time
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xq_user_trigram_book.modified_time
     *
     * @return the value of xq_user_trigram_book.modified_time
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public UserTrigramBook withModifiedTime(Date modifiedTime) {
        this.setModifiedTime(modifiedTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xq_user_trigram_book.modified_time
     *
     * @param modifiedTime the value for xq_user_trigram_book.modified_time
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", name=").append(name);
        sb.append(", sex=").append(sex);
        sb.append(", birthday=").append(birthday);
        sb.append(", residenceProvinceId=").append(residenceProvinceId);
        sb.append(", residenceCityId=").append(residenceCityId);
        sb.append(", residenceDistrictId=").append(residenceDistrictId);
        sb.append(", birthProvinceId=").append(birthProvinceId);
        sb.append(", birthCityId=").append(birthCityId);
        sb.append(", birthDistrictId=").append(birthDistrictId);
        sb.append(", relation=").append(relation);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append("]");
        return sb.toString();
    }
}