package com.xinguqe.xingque_api.mapper;

import com.xinguqe.xingque_api.entity.QuickLink;
import com.xinguqe.xingque_api.entity.QuickLinkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuickLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_quick_link
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    long countByExample(QuickLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_quick_link
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    int deleteByExample(QuickLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_quick_link
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_quick_link
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    int insert(QuickLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_quick_link
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    int insertSelective(QuickLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_quick_link
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    List<QuickLink> selectByExampleWithBLOBs(QuickLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_quick_link
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    List<QuickLink> selectByExample(QuickLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_quick_link
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    QuickLink selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_quick_link
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    int updateByExampleSelective(@Param("record") QuickLink record, @Param("example") QuickLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_quick_link
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("record") QuickLink record, @Param("example") QuickLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_quick_link
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    int updateByExample(@Param("record") QuickLink record, @Param("example") QuickLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_quick_link
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    int updateByPrimaryKeySelective(QuickLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_quick_link
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(QuickLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_quick_link
     *
     * @mbg.generated Tue Aug 27 15:17:49 CST 2024
     */
    int updateByPrimaryKey(QuickLink record);
}