package com.xinguqe.xingque_api.mapper;

import com.xinguqe.xingque_api.entity.UserBehavior;
import com.xinguqe.xingque_api.entity.UserBehaviorExample;
import java.util.List;

import com.xinguqe.xingque_api.entity.domain.UserBehaviorToolsCount;
import org.apache.ibatis.annotations.Param;

public interface UserBehaviorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_behavior
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    long countByExample(UserBehaviorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_behavior
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    int deleteByExample(UserBehaviorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_behavior
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_behavior
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    int insert(UserBehavior record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_behavior
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    int insertSelective(UserBehavior record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_behavior
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    List<UserBehavior> selectByExample(UserBehaviorExample example);
    List<UserBehaviorToolsCount> selectToolsCountByExample(UserBehaviorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_behavior
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    UserBehavior selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_behavior
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    int updateByExampleSelective(@Param("record") UserBehavior record, @Param("example") UserBehaviorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_behavior
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    int updateByExample(@Param("record") UserBehavior record, @Param("example") UserBehaviorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_behavior
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    int updateByPrimaryKeySelective(UserBehavior record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_behavior
     *
     * @mbg.generated Wed Aug 21 16:20:42 CST 2024
     */
    int updateByPrimaryKey(UserBehavior record);
}