package com.xinguqe.xingque_api.mapper;

import com.xinguqe.xingque_api.entity.UserTrigramBook;
import com.xinguqe.xingque_api.entity.UserTrigramBookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserTrigramBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    long countByExample(UserTrigramBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int deleteByExample(UserTrigramBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int insert(UserTrigramBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int insertSelective(UserTrigramBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    List<UserTrigramBook> selectByExample(UserTrigramBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    UserTrigramBook selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int updateByExampleSelective(@Param("record") UserTrigramBook record, @Param("example") UserTrigramBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int updateByExample(@Param("record") UserTrigramBook record, @Param("example") UserTrigramBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int updateByPrimaryKeySelective(UserTrigramBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_book
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int updateByPrimaryKey(UserTrigramBook record);
}