package com.xinguqe.xingque_api.mapper;

import com.xinguqe.xingque_api.entity.UserTrigramRecord;
import com.xinguqe.xingque_api.entity.UserTrigramRecordExample;
import com.xinguqe.xingque_api.entity.UserTrigramRecordWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserTrigramRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    long countByExample(UserTrigramRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int deleteByExample(UserTrigramRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int insert(UserTrigramRecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int insertSelective(UserTrigramRecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    List<UserTrigramRecordWithBLOBs> selectByExampleWithBLOBs(UserTrigramRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    List<UserTrigramRecord> selectByExample(UserTrigramRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    UserTrigramRecordWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int updateByExampleSelective(@Param("record") UserTrigramRecordWithBLOBs record, @Param("example") UserTrigramRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("record") UserTrigramRecordWithBLOBs record, @Param("example") UserTrigramRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int updateByExample(@Param("record") UserTrigramRecord record, @Param("example") UserTrigramRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int updateByPrimaryKeySelective(UserTrigramRecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(UserTrigramRecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_trigram_record
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int updateByPrimaryKey(UserTrigramRecord record);

    List<Integer> selectIdByExample(UserTrigramRecordExample example);
}