package com.xinguqe.xingque_api.mapper;

import com.xinguqe.xingque_api.entity.UserSuggest;
import com.xinguqe.xingque_api.entity.UserSuggestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserSuggestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_suggest
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    long countByExample(UserSuggestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_suggest
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int deleteByExample(UserSuggestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_suggest
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_suggest
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int insert(UserSuggest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_suggest
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int insertSelective(UserSuggest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_suggest
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    List<UserSuggest> selectByExampleWithBLOBs(UserSuggestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_suggest
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    List<UserSuggest> selectByExample(UserSuggestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_suggest
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    UserSuggest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_suggest
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int updateByExampleSelective(@Param("record") UserSuggest record, @Param("example") UserSuggestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_suggest
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("record") UserSuggest record, @Param("example") UserSuggestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_suggest
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int updateByExample(@Param("record") UserSuggest record, @Param("example") UserSuggestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_suggest
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int updateByPrimaryKeySelective(UserSuggest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_suggest
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(UserSuggest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_suggest
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int updateByPrimaryKey(UserSuggest record);
}