package com.xinguqe.xingque_api.mapper;

import com.xinguqe.xingque_api.entity.UserConfig;
import com.xinguqe.xingque_api.entity.UserConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_config
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    long countByExample(UserConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_config
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int deleteByExample(UserConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_config
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_config
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int insert(UserConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_config
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int insertSelective(UserConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_config
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    List<UserConfig> selectByExample(UserConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_config
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    UserConfig selectFirstByExample(UserConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_config
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    UserConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_config
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int updateByExampleSelective(@Param("record") UserConfig record, @Param("example") UserConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_config
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int updateByExample(@Param("record") UserConfig record, @Param("example") UserConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_config
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int updateByPrimaryKeySelective(UserConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user_config
     *
     * @mbg.generated Fri Aug 09 15:04:59 CST 2024
     */
    int updateByPrimaryKey(UserConfig record);
}