package com.xinguqe.xingque_api.mapper;

import com.xinguqe.xingque_api.entity.User;
import com.xinguqe.xingque_api.entity.UserExample;
import java.util.List;

import com.xinguqe.xingque_api.entity.domain.UserRegionStatistics;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    List<User> selectByExample(UserExample example);

    User selectFirstByExample(UserExample example);
    List<UserRegionStatistics> selectRegionCountByExample(UserExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *s
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xq_user
     *
     * @mbg.generated Thu Aug 22 17:37:50 CST 2024
     */
    int updateByPrimaryKey(User record);
}